## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_module('obs', ['network', 'applications'])
    obj.source = [
        'model/obs-channel.cc',
	'model/obs-device.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'obs'
    headers.source = [
        'model/obs-channel.h',
	'model/obs-device.h',
        ]


    bld.add_subdirs('example')

#    bld.ns3_python_bindings()
